/**
 * Types shared between the server (camera capture, timelapse recording) and
 * the UI (camera tab). Keep this file free of node/browser-specific imports.
 */

export type CameraKind = "device" | "libcamera" | "url" | "rtsp";

export type CameraRotation = 0 | 90 | 180 | 270;

export interface CameraConfig {
  /** Stable identifier, generated by the server. */
  id: string;
  /** Display name. */
  name: string;
  /**
   * How frames are obtained:
   * - `device`: a local capture device (`/dev/video0` on Linux, an avfoundation index on macOS,
   *   or a dshow name on Windows) read through ffmpeg.
   * - `libcamera`: a Raspberry Pi camera module read through `rpicam-vid` / `libcamera-vid`.
   * - `url`: an HTTP(S) URL serving either a single JPEG (polled) or an MJPEG multipart stream.
   * - `rtsp`: an RTSP stream read through ffmpeg.
   */
  kind: CameraKind;
  /** Device path, device index/name, or URL depending on `kind`. */
  source: string;
  /** Requested capture resolution such as `1920x1080`. Empty means "source default". */
  resolution: string;
  /**
   * Optional input pixel format / codec for `device` sources, e.g. `mjpeg` or `yuyv422`.
   * Most USB webcams only deliver high resolutions in `mjpeg`.
   */
  inputFormat: string;
  /** Frames per second the source is sampled at while active. Timelapse frames are taken from this stream. */
  fps: number;
  /** Rotation applied when previewing and rendering (frames are stored as captured). */
  rotate: CameraRotation;
  /** What triggers this camera's timelapse frames. Empty follows the timelapse settings. */
  trigger: TimelapseTrigger | "";
  /** Disabled cameras are not previewed or recorded. */
  enabled: boolean;
}

export type CameraState = "idle" | "starting" | "live" | "error";

export interface CameraStatus {
  state: CameraState;
  error: string | null;
  /** Unix ms timestamp of the most recent frame, or null. */
  lastFrameAt: number | null;
  /** Dimensions of the most recent frame, when known. */
  width: number | null;
  height: number | null;
  /** Number of frames received since the source was last started. */
  frames: number;
}

export type CameraWithStatus = CameraConfig & { status: CameraStatus };

/** A format a local capture device can deliver, as listed by ffmpeg. */
export interface VideoDeviceFormat {
  /** Value for a camera's `inputFormat`, e.g. `mjpeg` or `yuyv422`. */
  name: string;
  /** The driver's description, e.g. `Motion-JPEG` or `YUYV 4:2:2`. */
  description: string;
  compressed: boolean;
  /** Frame sizes such as `1920x1080`, widest first. Empty when the device accepts any size within a range. */
  resolutions: string[];
}

/** A capture device found on the server, offered in the camera form. */
export interface VideoDevice {
  /** Name reported by the driver, e.g. `HD Pro Webcam C920`. */
  name: string;
  /** Kernel device node, e.g. `/dev/video2`. */
  node: string;
  /**
   * What to store as a camera's `source`: a /dev/v4l link that survives replugging and reboots
   * when there is a usable one, otherwise `node`.
   */
  source: string;
  /** Every path that refers to this device, including `source` and `node`. */
  paths: string[];
  formats: VideoDeviceFormat[];
  /** Configured cameras that already use this device. */
  usedBy: Array<{ id: string; name: string }>;
}

export interface VideoDevicesResponse {
  devices: VideoDevice[];
  /** False where saxi cannot list devices (anything but Linux for now). */
  supported: boolean;
}

/** Sorts frame sizes such as `1280x720` widest first, then tallest, dropping duplicates. */
export function sortResolutions(resolutions: Iterable<string>): string[] {
  const size = (r: string) => r.split("x").map(Number);
  return [...new Set(resolutions)].sort((a, b) => {
    const [aw, ah] = size(a);
    const [bw, bh] = size(b);
    return bw - aw || bh - ah;
  });
}

/**
 * What triggers timelapse frames while plotting:
 * - `penLift`: every pen lift, once the pen is off the paper.
 * - `penDown`: while the pen is down and drawing; no frames of the blank page or the finished drawing,
 *   which suits a camera on the pen carriage.
 * - `interval`: a fixed interval.
 * - `targetFrames`: an interval derived from the plot duration, for a set number of frames.
 */
export type TimelapseTrigger = "penLift" | "penDown" | "interval" | "targetFrames";

export const TIMELAPSE_TRIGGERS: TimelapseTrigger[] = ["penLift", "penDown", "interval", "targetFrames"];

export interface RenderSettings {
  /** Output frame rate of the rendered video. */
  fps: number;
  /** x264 constant rate factor: lower is higher quality (18 is visually lossless-ish). */
  crf: number;
  /** x264 preset. Slower presets are smaller at equal quality but take much longer on a Pi. */
  preset: string;
  /** Seconds the final frame is held at the end of the video. */
  postRollSeconds: number;
  /** Also render a side-by-side / grid video combining all cameras. */
  composite: boolean;
}

export interface TimelapseSettings {
  /** Automatically record a timelapse for every plot. */
  enabled: boolean;
  trigger: TimelapseTrigger;
  /** Seconds between frames for the `interval` trigger. */
  intervalSeconds: number;
  /** Desired number of frames for the `targetFrames` trigger; the interval is derived from the plan duration. */
  targetFrames: number;
  /** Minimum seconds between frames for the pen triggers (pen lifts can be very frequent). */
  minIntervalSeconds: number;
  /**
   * For `penDown`: take a frame at least this often while drawing, even when the pen isn't down long enough for
   * one (short lines, stippling). 0 turns this off.
   */
  maxIntervalSeconds: number;
  /** Milliseconds to wait after a trigger before grabbing the frame, letting the machine settle. Not for `penDown`. */
  captureDelayMs: number;
  /** Render videos automatically when a recording finishes (requires ffmpeg). */
  autoRender: boolean;
  render: RenderSettings;
}

export type TimelapseStatus = "recording" | "finished" | "cancelled" | "failed";

export interface TimelapseCameraInfo {
  id: string;
  name: string;
  rotate: CameraRotation;
  /** What triggered this camera's frames. Missing in recordings from before cameras had their own trigger. */
  trigger?: TimelapseTrigger;
  /** Number of frame files stored for this camera. */
  frameCount: number;
  width: number | null;
  height: number | null;
}

export interface TimelapseRender {
  /** File name inside the session's `renders` directory. */
  file: string;
  /** Camera id, or `composite` for the multi-camera video. */
  camera: string;
  fps: number;
  createdAt: string;
  sizeBytes: number;
}

export interface TimelapseSession {
  id: string;
  name: string;
  startedAt: string;
  finishedAt: string | null;
  status: TimelapseStatus;
  source: "plot" | "manual";
  trigger: TimelapseTrigger;
  /** Number of moments at which frames were captured (by any camera). */
  frameCount: number;
  cameras: TimelapseCameraInfo[];
  renders: TimelapseRender[];
}

export interface RenderJob {
  id: string;
  sessionId: string;
  /** Camera id or `composite`. */
  camera: string;
  status: "running" | "done" | "error";
  /** 0..1 */
  progress: number;
  error: string | null;
  output: string | null;
  startedAt: string;
}

export interface Capabilities {
  ffmpeg: boolean;
  ffmpegVersion: string | null;
  libcamera: boolean;
  platform: string;
}

export interface TimelapseStatusResponse {
  settings: TimelapseSettings;
  active: TimelapseSession | null;
  renderJobs: RenderJob[];
  capabilities: Capabilities;
  dataDir: string;
  plotting: boolean;
}

export const defaultRenderSettings: RenderSettings = {
  fps: 24,
  crf: 18,
  preset: "medium",
  postRollSeconds: 2,
  composite: true,
};

export const defaultTimelapseSettings: TimelapseSettings = {
  enabled: false,
  trigger: "penLift",
  intervalSeconds: 5,
  targetFrames: 240,
  minIntervalSeconds: 2,
  maxIntervalSeconds: 10,
  captureDelayMs: 250,
  autoRender: true,
  render: defaultRenderSettings,
};

export const defaultCameraConfig: Omit<CameraConfig, "id"> = {
  name: "",
  kind: "device",
  source: "/dev/video0",
  resolution: "",
  inputFormat: "",
  fps: 2,
  rotate: 0,
  trigger: "",
  enabled: true,
};
